[[drone]]
id = 1
connected_node_ids = [0, 2]
pdr = 0.00

[[drone]]
id = 2
connected_node_ids = [1, 3]
pdr = 0.00

[[drone]]
id = 3
connected_node_ids = [2]
pdr = 0.00

[[client]]
id = 0
connected_drone_ids = [1]

[[server]]
id = 100
connected_drone_ids = []
