[[drone]]
id = 1
connected_node_ids = [0, 5, 6]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [5,6]
pdr = 0.03

[[drone]]
id = 3
connected_node_ids = [7,8]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [7,8]
pdr = 0.14

[[drone]]
id = 5
connected_node_ids = [1,2,9]
pdr = 0.14

[[drone]]
id = 6
connected_node_ids = [1,2,10]
pdr = 0.14

[[drone]]
id = 7
connected_node_ids = [9,3,4]
pdr = 0.14

[[drone]]
id = 8
connected_node_ids = [10,3,4]
pdr = 0.14

[[drone]]
id = 9
connected_node_ids = [5,7,10]
pdr = 0.14

[[drone]]
id = 10
connected_node_ids = [9,6,8]
pdr = 0.14


[[client]]
id = 0
connected_drone_ids = [1]

[[server]]
id = 14
connected_drone_ids = []

